import Lean
import MLTStar

/-!
# Axiom audit

Reports, for every named result in the development, which of the three
non-definitional axioms its proof term actually reaches:

* `a9`      — `MLTStar.Extensional.typeExtensionality`
* `a4`      — `MLTStar.Grounded.grounded`
* `a13-15`  — the constants of `MLTStar.Constants`

A result that names an axiom in its hypotheses need not use it, so this walks
the proof terms rather than the statements.  Run from the `lean` directory:

```sh
lake build
LEAN_PATH=.lake/build/lib/lean lean scripts/AxiomAudit.lean
```

Output is one tab-separated row per declaration: kind (`thm`/`def`), whether it
was written in a source file rather than generated by Lean (`src`/`gen`), the
defining module, the name, the axioms it reaches, and its direct
dependencies within `MLTStar`.
`derivation-graph.html` is drawn from the `thm`+`src` rows.
-/

open Lean Elab Command

/-- The declarations that mark a use of each axiom. -/
def axiomMarkers : List (Name × String) :=
  [(`MLTStar.Extensional.typeExtensionality, "a9"),
   (`MLTStar.Grounded.grounded, "a4")] ++
  [`MLTStar.Constants.cIndividual, `MLTStar.Constants.cFot, `MLTStar.Constants.cSot,
   `MLTStar.Constants.cIndividual_spec, `MLTStar.Constants.cFot_spec,
   `MLTStar.Constants.cSot_spec].map (·, "a13-15")

run_cmd do
  let env ← getEnv
  let interesting (n : Name) : Bool := (`MLTStar).isPrefixOf n && !n.isInternal
  -- direct dependencies of every declaration, from its type and its value
  let mut dep : Std.HashMap Name (Array Name) := {}
  for (n, ci) in env.constants.toList do
    if interesting n then
      let used := ci.type.getUsedConstants ++
        (match ci.value? with | some v => v.getUsedConstants | none => #[])
      dep := dep.insert n (used.filter fun m => interesting m && m != n).toList.eraseDups.toArray
  -- transitive closure
  let rec reach (n : Name) (seen : NameSet) : NameSet := Id.run do
    let mut s := seen
    for d in dep.getD n #[] do
      unless s.contains d do
        s := reach d (s.insert d)
    return s
  let mut rows : Array String := #[]
  for (n, ds) in dep.toList do
    let isThm := (env.find? n).any fun ci => match ci with | .thmInfo _ => true | _ => false
    -- declarations Lean generates (recursors, equation lemmas, projections) carry
    -- no source range; only hand-written ones are counted as results
    let src := (← findDeclarationRanges? n).isSome
    let r := reach n {}
    let ax := (axiomMarkers.filterMap fun (m, tag) => if r.contains m then some tag else none).eraseDups
    let ax := if ax.isEmpty then "-" else String.intercalate "," ax
    rows := rows.push s!"{if isThm then "thm" else "def"}\t{if src then "src" else "gen"}\t{n}\t{ax}\t{String.intercalate "," (ds.toList.map toString)}"
  for r in rows.qsort (· < ·) do IO.println r
